// This is a file that is essentially our csv parser functionality. Here we take the reports generated by career services,
// parse them for the company profile data, and populate our DB table related to the companies with the info gathered.

// Create a data structure for a "Company"
export type Company = {
    // Here are the fields we would need to populate for company profiles.
    orgName: string;
    logo?: string; // This one I'm not so sure about since we don't have an example to work with, data type might need changed
    majors: string[];
    posTitles: string[];
    posTypes: string[];
    compDesc?: string;
    website?: string;
    visaSponsorship?: string;
}

// Get the total number of companies
export type ParseOutput = { companies: Company[]; total: number };

// This is a list of the header names, so that they can be easily changed or addended
export type HeaderMap = {
    orgName: string;
    logo: string;
    majors: string;
    posTitles: string;
    posTypes: string;
    compDesc: string;
    website: string;
    visaSponsorship: string;
}

export const defaultHeaderMap: HeaderMap = {
  orgName: "Organization Name",
  logo: "Logo",
  majors: "Majors",
  posTitles: "Position Titles",
  posTypes: "Position Types",
  compDesc: "Company Description",
  website: "Website",
  visaSponsorship: "Visa Sponsorship",
};

// Here is the actual parser function
// Supports quoted vals and should split rows with commas or newlines if needed
function parseReport(text: string): string[][] {
    const rows: string[][] = [];
    let current = "" // current cell
    let row: string[] = []; // current row
    let inQuotes = false; // bool for if we are inside of quotes

    for(let i = 0; i < text.length; i++){
        const character = text[i];

        if(inQuotes){
            if(character === '"'){
                inQuotes = false; // set quotes to false once we get to the next quote mark
            } else {
                // normal character
                current += character;
            }
        } else {
            if(character === '"'){
                inQuotes = true;
            } else if(character === ",") {
                //since a comma is the end of a cell, we go to the next cell
                row.push(current);
                current = "";
            } else if(character === "\n"){
                // since newline is the end of a row, go to next row
                row.push(current);
                rows.push(row);
                row = [];
                current = "";
            } else {
                current += character;
            }

        }
    }
    row.push(current);
    rows.push(row);

    // drop a trailing empty line if present
    if (rows.length && rows[rows.length - 1].every(c => c === "")) {
        rows.pop();
    }
    return rows;
}

/*
Need to convert the fields into actual array structures
"Computer Science; Software Engineering" -> ["Computer Science", "Software Engineering"]
This does it using both semicolons and commas as seperators.
*/
const fieldsAsList = (s?: string | null): string[] =>
(s ?? "").split(/[;,]/).map(x => x.trim()).filter(Boolean);

/*
This is a grabber for cells
*/
const getCell = (row: string[], colIdx: number): string | undefined =>
  colIdx >= 0 && colIdx < row.length ? row[colIdx] : undefined;
/*
This is the actual parser logic. Uses our pre-made list of headers.
*/
export function parseCompaniesFromCsv(opts: {
    csvText: string;
    headermap?: HeaderMap;
}): ParseOutput {
    const headerMap = opts.headermap ?? defaultHeaderMap;
    // Set the CSV to our text we need to parse
    const {csvText} = opts;
    // If the text is empty/ does not exist, then there are no companies.
    if(!csvText) return { companies: [], total: 0};

    const rows = parseReport(csvText);
    const headers = rows[0].map(h => h.trim().toLowerCase()); //normalize the headers to all lowercase in case there's some weird typo
    const data = rows.slice(1);

    const idx = (headerName: string) =>
    headers.findIndex(h => h === headerName.toLowerCase());

    const col = {
        orgName: idx(headerMap.orgName),
        logo: idx(headerMap.logo),
        majors: idx(headerMap.majors),
        posTitles: idx(headerMap.posTitles),
        posTypes: idx(headerMap.posTypes),
        compDesc: idx(headerMap.compDesc),
        website: idx(headerMap.website),
        visaSponsorship: idx(headerMap.visaSponsorship),
    };

    // now we build our company objects
    const companies: Company[] = [];
    for(const row of data) {
        const orgName = getCell(row, col.orgName)?.trim() ?? "";
        if (!orgName) continue; // skip blank rows

        const logo = getCell(row, col.logo)?.trim();
        const compDesc = getCell(row, col.compDesc)?.trim();
        const website = getCell(row, col.website)?.trim();
        const visaSponsorship = getCell(row, col.visaSponsorship)?.trim();

        const majors = fieldsAsList(getCell(row, col.majors));
        const posTitles = fieldsAsList(getCell(row, col.posTitles));
        const posTypes = fieldsAsList(getCell(row, col.posTypes));

        const company: Company = {
            orgName,
            majors,
            posTitles,
            posTypes,
            logo,
            compDesc,
            website,
            visaSponsorship
        };
        companies.push(company);
    }
    return{companies, total: companies.length};
}